### ISSUE TITLE
Minor UI Glitch

### ISSUE THREAD

**Issue by JackWolfskin42** [ioBroker/ioBroker.ham-wemo#1]
Mit Chrome sieht die Adapter config wie folgt aus:
![image](https://user-images.githubusercontent.com/38285253/41790521-21746754-7653-11e8-9852-4b15a6495f69.png)

**Comment by GermanBluefox** [comment]
Fixed in 0.2.2

**Comment by JackWolfskin42** [comment]
Fixed!

**Comment by Apollon77** [comment]
Version already on npm
