### ISSUE TITLE
Wemo Maker Sensor state

### ISSUE THREAD

**Issue by BenjaminK87** [ioBroker/ioBroker.ham-wemo#2]
Hi, would it be possible to get the Sensor state of the Wemo Maker also as an Object in ioBroker (like the "On" State)? At the moment I can only see it in the debug log of the adapter:
[2018-7-6 11:31:06] [WeMo Platform] Wasserstand - Sensor: Not detected
[2018-7-6 11:32:19] [WeMo Platform] Wasserstand - Sensor: Detected

**Comment by Apollon77** [comment]
ham based adapter can only offer objects that were also offered by the homebridge plugin as characteristic. So it seems that this info is not offered as characteristic ... you would need to talk to the homebrdge-plugin developer to get this as characteristic
