### ISSUE TITLE
homebridge plugin move

### ISSUE THREAD

**Issue by bwp91** [ioBroker/ioBroker.ham-wemo#33]
Hey.

Just a heads up, the `homebridge-platform-wemo` plugin has moved to `homebridge-wemo`.

Also in the homebridge configuration, the line `"platform": "BelkinWeMo”` has changed to `"platform": "Wemo"`.

Thanks!

**Comment by Apollon77** [comment]
@bwp91 the rest stays the same?

**Comment by Apollon77** [comment]
And needs at least homebridge 1.3.5

**Comment by bwp91** [comment]
Yes apart from the config change above, there aren’t any other breaking changes.

The lowest version of homebridge that will work is 1.3.0, however in the package json file I like to keep the homebridge version up to date so that currently states 1.3.5

**Comment by Apollon77** [comment]
Ok, I plan to update the "used homebridge versioN" anyway ... so it just means I need to do that together. Thank you!

**Comment by Apollon77** [comment]
Will be in next verison which bases on homebridge 1.4.1

**Comment by Apollon77** [comment]
Done in 3.0.0
